name: Hello
description: 'Greet someone'
inputs:
  who:
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - name: Random Number Generator
      id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash
    - name: Say Goodbye
      run: echo Goodbye
      shell: bash
    - name: Print input context
      run: echo "${{ toJson(inputs) }}"
      shell: bash
    - name: Print github context
      shell: bash
      run: |
        echo `
          Ref: ${{ github.ref }}
          SHA: ${{ github.sha }}
          Run Number: ${{ github.run_number }}
          Head Ref: ${{ github.head_ref }}
          Base Ref: ${{ github.base_ref }}
          Event Name: ${{ github.event_name }}
        `
