name: CI
on:
  pull_request:
    branches: main
  push:
    branches: main
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo source code
        uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!
  trigger-cd:
    name: CD
    needs: ci
    if: github.event_name != 'pull_request'
    uses: ./.github/workflows/cd.yml
    with:
      environment: STAGING
