name: CI
on:
  pull_request:
    branches: main
  push:
    branches: main
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo source code
        uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello
      - name: Check
        if: ${{ !startsWith(github.ref, 'refs/tags/v') && github.ref != 'refs/heads/main' }}
        run: |
          { echo "Wrong branch/tag"; } 2>
          /dev/null && exit 1
      - name: compo
        uses: ./.github/actions/hello
        with:
          who: "Hello there"
  ci-matrix:
    name: CI Matrix
    needs: ci
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service: [ svc1, svc2, svc3 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Something 1
        run: echo "${{ matrix.service }}"
      - name: Something 2
        run: echo "${{ matrix.service }}"
  trigger-cd:
    name: CD
    needs: ci-matrix
    if: github.event_name != 'pull_request'
    uses: ./.github/workflows/cd.yml
    with:
      environment: STAGING
