name: DB Migrations
concurrency: PRODUCTION
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run migrations on'
        required: true
        type: environment
      service:
        description: 'Service to run migrations on'
        required: true
        type: choice
        options:
          - ledgersvc
      database:
        description: 'Which database?'
        required: true
        type: string
      direction:
        description: 'Direction of migration (up/down)'
        required: true
        type: choice
        options:
          - up
          - down
jobs:
  prepare:
    name: Prepare # Using separate job to be able to print before the approval stage triggered by the `environment` setting
    runs-on: ubuntu-latest
    steps:
      - name: Print Inputs
        run: echo "${{ toJSON(inputs) }}"
      - uses: actions/checkout@v3
      - uses: ./.github/actions/ensure-main-release
  run-migrations:
    name: Test golib
    needs: [prepare]
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Run
        run: echo Running...
