name: include-cd
on:
  push:
    branches: main
jobs:
  build-and-test:
    uses: ./.github/workflows/include-ci.yml
  deploy-to-staging:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
