name: "CodeQL Advanced"
on:
  push:
    branches: [ "main" ]
jobs:
  analyze:
    name: Analyze (${{ matrix.language }})
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - language: go
            build-mode: none
          - language: actions
            build-mode: none
    steps:
      - name: Checkout repository
        run: echo "${{ matrix.language }} & ${{ matrix.build-mode }}"
