name: "CodeQL Advanced"
on:
  push:
    branches: [ "main" ]
jobs:
  analyze:
    name: Analyze (${{ matrix.language }})
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - service: golib
            type: library
            language: something
          - service: ledgersvc
            type: service
            language: go
          - service: svc2
            type: service
            language: typescript
    steps:
      - name: Checkout repository
        run: echo "${{ matrix.language }} & ${{ matrix.build-mode }}"
