name: push-cd
on:
  workflow_call:
jobs:
  check-some-stuff:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
  deploy-to-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
