name: push-cd
on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment'
        type: string
        required: true
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        type: environment
        required: true
jobs:
  prepare-for-deployment:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Step1
        run: echo Env Secret is $ENV_SECRET
        env:
          ENV_SECRET: ${{ secrets.ENV_SECRET }}
      - name: Step2
        run: echo Step2
      - name: Step3
        run: echo Step3
      - name: Step4
        run: echo Step4
  deploy-svc1:
    environment: ${{ inputs.environment }}
    needs: prepare-for-deployment
    runs-on: ubuntu-latest
    steps:
      - name: Step1
        run: echo Step1
      - name: Step2
        run: echo Step2
      - name: Step3
        run: echo Step3
      - name: Step4
        run: echo Step4
      - name: Step5
        run: echo Step5
      - name: Step6
        run: echo Step6
      - name: Step7
        run: echo Step7
  deploy-svc2:
    environment: ${{ inputs.environment }}
    needs: prepare-for-deployment
    runs-on: ubuntu-latest
    steps:
      - name: Step1
        run: echo Step1
      - name: Step2
        run: echo Step2
      - name: Step3
        run: echo Step3
      - name: Step4
        run: echo Step4
      - name: Step5
        run: echo Step5
      - name: Step6
        run: echo Step6
      - name: Step7
        run: echo Step7
  deploy-svc3:
    environment: ${{ inputs.environment }}
    needs: prepare-for-deployment
    runs-on: ubuntu-latest
    steps:
      - name: Step1
        run: echo Step1
      - name: Step2
        run: echo Step2
