name: push-ci
on:
  pull_request:
    branches: main
  push:
    branches: main
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo source code
        uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!
  trigger-cd:
    needs: build-and-test
    if: github.event_name != 'pull_request'
    uses: ./.github/workflows/push-cd.yml
    with:
      environment: staging
