name: push-cd
on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment'
        type: string
        required: true
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        type: environment
        required: true
jobs:
  prepare-for-deployment:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
  deploy-svc1:
    needs: prepare-for-deployment
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
  deploy-svc2:
    needs: prepare-for-deployment
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
