name: Release
concurrency: PRODUCTION
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
jobs:
  trigger-cd:
    name: CD
    uses: ./.github/workflows/cd.yml
    with:
      environment: PRODUCTION
